from .utility_nodes import UTIL_NODE_CLASS_MAPPINGS as BASE_CLASS_MAPPINGS
from .utility_nodes import UTIL_NODE_DISPLAY_NAME_MAPPINGS as BASE_DISPLAY_NAME_MAPPINGS
from .yellow_tint_cleaner_node import UTIL_NODE_CLASS_MAPPINGS as YT_CLASS_MAPPINGS
from .yellow_tint_cleaner_node import UTIL_NODE_DISPLAY_NAME_MAPPINGS as YT_DISPLAY_NAME_MAPPINGS

UTIL_NODE_CLASS_MAPPINGS = {
    **BASE_CLASS_MAPPINGS,
    **YT_CLASS_MAPPINGS
}

UTIL_NODE_DISPLAY_NAME_MAPPINGS = {
    **BASE_DISPLAY_NAME_MAPPINGS,
    **YT_DISPLAY_NAME_MAPPINGS
}

__all__ = ["UTIL_NODE_CLASS_MAPPINGS", "UTIL_NODE_DISPLAY_NAME_MAPPINGS"]
