# Individual model family imports
from .flux_nodes import FLUX_NODE_CLASS_MAPPINGS, FLUX_NODE_DISPLAY_NAME_MAPPINGS
from .google_nodes import GOOGLE_NODE_CLASS_MAPPINGS, GOOGLE_NODE_DISPLAY_NAME_MAPPINGS
from .luma_nodes import LUMA_NODE_CLASS_MAPPINGS, LUMA_NODE_DISPLAY_NAME_MAPPINGS
from .bytedance_nodes import BYTEDANCE_NODE_CLASS_MAPPINGS, BYTEDANCE_NODE_DISPLAY_NAME_MAPPINGS
from .ideogram_nodes import IDEOGRAM_NODE_CLASS_MAPPINGS, IDEOGRAM_NODE_DISPLAY_NAME_MAPPINGS
from .recraft_nodes import RECRAFT_NODE_CLASS_MAPPINGS, RECRAFT_NODE_DISPLAY_NAME_MAPPINGS
from .qwen_nodes import QWEN_NODE_CLASS_MAPPINGS, QWEN_NODE_DISPLAY_NAME_MAPPINGS
from .nano_banana_nodes import NANO_BANANA_NODE_CLASS_MAPPINGS, NANO_BANANA_NODE_DISPLAY_NAME_MAPPINGS
from .xai_nodes import XAI_NODE_CLASS_MAPPINGS, XAI_NODE_DISPLAY_NAME_MAPPINGS

#Existing imports
from .llm_api_nodes import LLM_NODE_CLASS_MAPPINGS, LLM_NODE_DISPLAY_NAME_MAPPINGS
from .midjourney_proxy_node import MJ_PROXY_NODE_CLASS_MAPPINGS, MJ_PROXY_NODE_DISPLAY_NAME_MAPPINGS
from .openai_image_nodes import OPENAI_IMAGE_NODE_CLASS_MAPPINGS, OPENAI_IMAGE_NODE_DISPLAY_NAME_MAPPINGS
from .stable_diffusion_nodes import STABLE_DIFFUSION_NODE_CLASS_MAPPINGS, STABLE_DIFFUSION_NODE_DISPLAY_NAME_MAPPINGS
from .utility_nodes import UTIL_NODE_CLASS_MAPPINGS, UTIL_NODE_DISPLAY_NAME_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **FLUX_NODE_CLASS_MAPPINGS,
    **GOOGLE_NODE_CLASS_MAPPINGS,
    **LUMA_NODE_CLASS_MAPPINGS,
    **BYTEDANCE_NODE_CLASS_MAPPINGS,
    **IDEOGRAM_NODE_CLASS_MAPPINGS,
    **RECRAFT_NODE_CLASS_MAPPINGS,
    **QWEN_NODE_CLASS_MAPPINGS,
    **NANO_BANANA_NODE_CLASS_MAPPINGS,
    **XAI_NODE_CLASS_MAPPINGS,
    **LLM_NODE_CLASS_MAPPINGS,
    **MJ_PROXY_NODE_CLASS_MAPPINGS,
    **OPENAI_IMAGE_NODE_CLASS_MAPPINGS,
    **STABLE_DIFFUSION_NODE_CLASS_MAPPINGS,
    **UTIL_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FLUX_NODE_DISPLAY_NAME_MAPPINGS,
    **GOOGLE_NODE_DISPLAY_NAME_MAPPINGS,
    **LUMA_NODE_DISPLAY_NAME_MAPPINGS,
    **BYTEDANCE_NODE_DISPLAY_NAME_MAPPINGS,
    **IDEOGRAM_NODE_DISPLAY_NAME_MAPPINGS,
    **RECRAFT_NODE_DISPLAY_NAME_MAPPINGS,
    **QWEN_NODE_DISPLAY_NAME_MAPPINGS,
    **NANO_BANANA_NODE_DISPLAY_NAME_MAPPINGS,
    **XAI_NODE_DISPLAY_NAME_MAPPINGS,
    **LLM_NODE_DISPLAY_NAME_MAPPINGS,
    **MJ_PROXY_NODE_DISPLAY_NAME_MAPPINGS,
    **OPENAI_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **STABLE_DIFFUSION_NODE_DISPLAY_NAME_MAPPINGS,
    **UTIL_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]