from .api_nodes import API_NODE_CLASS_MAPPINGS, API_NODE_DISPLAY_NAME_MAPPINGS
from .llm_api_nodes import LLM_NODE_CLASS_MAPPINGS, LLM_NODE_DISPLAY_NAME_MAPPINGS
from .midjourney_proxy_node import MJ_PROXY_NODE_CLASS_MAPPINGS, MJ_PROXY_NODE_DISPLAY_NAME_MAPPINGS
from .utility_nodes import UTIL_NODE_CLASS_MAPPINGS, UTIL_NODE_DISPLAY_NAME_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **API_NODE_CLASS_MAPPINGS,
    **LLM_NODE_CLASS_MAPPINGS,
    **MJ_PROXY_NODE_CLASS_MAPPINGS,
    **UTIL_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **API_NODE_DISPLAY_NAME_MAPPINGS,
    **LLM_NODE_DISPLAY_NAME_MAPPINGS,
    **MJ_PROXY_NODE_DISPLAY_NAME_MAPPINGS,
    **UTIL_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]