# Import from organized folders
# LLM nodes
from .llm import LLM_NODE_CLASS_MAPPINGS, LLM_NODE_DISPLAY_NAME_MAPPINGS

# Utility nodes
from .util import UTIL_NODE_CLASS_MAPPINGS, UTIL_NODE_DISPLAY_NAME_MAPPINGS

# Image generation nodes
from .img import (
    FLUX_NODE_CLASS_MAPPINGS, FLUX_NODE_DISPLAY_NAME_MAPPINGS,
    GOOGLE_NODE_CLASS_MAPPINGS, GOOGLE_NODE_DISPLAY_NAME_MAPPINGS,
    LUMA_NODE_CLASS_MAPPINGS, LUMA_NODE_DISPLAY_NAME_MAPPINGS,
    BYTEDANCE_NODE_CLASS_MAPPINGS, BYTEDANCE_NODE_DISPLAY_NAME_MAPPINGS,
    IDEOGRAM_NODE_CLASS_MAPPINGS, IDEOGRAM_NODE_DISPLAY_NAME_MAPPINGS,
    RECRAFT_NODE_CLASS_MAPPINGS, RECRAFT_NODE_DISPLAY_NAME_MAPPINGS,
    QWEN_NODE_CLASS_MAPPINGS, QWEN_NODE_DISPLAY_NAME_MAPPINGS,
    NANO_BANANA_NODE_CLASS_MAPPINGS, NANO_BANANA_NODE_DISPLAY_NAME_MAPPINGS,
    XAI_NODE_CLASS_MAPPINGS, XAI_NODE_DISPLAY_NAME_MAPPINGS,
    MJ_PROXY_NODE_CLASS_MAPPINGS, MJ_PROXY_NODE_DISPLAY_NAME_MAPPINGS,
    OPENAI_IMAGE_NODE_CLASS_MAPPINGS, OPENAI_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    STABLE_DIFFUSION_NODE_CLASS_MAPPINGS, STABLE_DIFFUSION_NODE_DISPLAY_NAME_MAPPINGS
)

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **FLUX_NODE_CLASS_MAPPINGS,
    **GOOGLE_NODE_CLASS_MAPPINGS,
    **LUMA_NODE_CLASS_MAPPINGS,
    **BYTEDANCE_NODE_CLASS_MAPPINGS,
    **IDEOGRAM_NODE_CLASS_MAPPINGS,
    **RECRAFT_NODE_CLASS_MAPPINGS,
    **QWEN_NODE_CLASS_MAPPINGS,
    **NANO_BANANA_NODE_CLASS_MAPPINGS,
    **XAI_NODE_CLASS_MAPPINGS,
    **LLM_NODE_CLASS_MAPPINGS,
    **MJ_PROXY_NODE_CLASS_MAPPINGS,
    **OPENAI_IMAGE_NODE_CLASS_MAPPINGS,
    **STABLE_DIFFUSION_NODE_CLASS_MAPPINGS,
    **UTIL_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FLUX_NODE_DISPLAY_NAME_MAPPINGS,
    **GOOGLE_NODE_DISPLAY_NAME_MAPPINGS,
    **LUMA_NODE_DISPLAY_NAME_MAPPINGS,
    **BYTEDANCE_NODE_DISPLAY_NAME_MAPPINGS,
    **IDEOGRAM_NODE_DISPLAY_NAME_MAPPINGS,
    **RECRAFT_NODE_DISPLAY_NAME_MAPPINGS,
    **QWEN_NODE_DISPLAY_NAME_MAPPINGS,
    **NANO_BANANA_NODE_DISPLAY_NAME_MAPPINGS,
    **XAI_NODE_DISPLAY_NAME_MAPPINGS,
    **LLM_NODE_DISPLAY_NAME_MAPPINGS,
    **MJ_PROXY_NODE_CLASS_MAPPINGS,
    **OPENAI_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **STABLE_DIFFUSION_NODE_DISPLAY_NAME_MAPPINGS,
    **UTIL_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]